export const ERROR_CODES = {
  // ── Auth Guard ──
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_ADMIN_ONLY: "AUTH_ADMIN_ONLY",

  // ── JWT ──
  JWT_INVALID: "JWT_INVALID",
  JWT_EXPIRED: "JWT_EXPIRED",

  // ── Token ──
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",

  // ── Login ──
  LOGIN_ACCOUNT_LOCKED: "LOGIN_ACCOUNT_LOCKED",
  LOGIN_INVALID_EMAIL: "LOGIN_INVALID_EMAIL",
  LOGIN_ACCOUNT_INACTIVE: "LOGIN_ACCOUNT_INACTIVE",
  LOGIN_EMAIL_NOT_VERIFIED: "LOGIN_EMAIL_NOT_VERIFIED",
  LOGIN_INVALID_CREDENTIALS: "LOGIN_INVALID_CREDENTIALS",
  LOGIN_OTP_COOLDOWN: "LOGIN_OTP_COOLDOWN",
  LOGIN_OTP_RESEND_LIMIT: "LOGIN_OTP_RESEND_LIMIT",
  LOGIN_OTP_LOCKED: "LOGIN_OTP_LOCKED",
  LOGIN_OTP_INVALID: "LOGIN_OTP_INVALID",
  LOGIN_MAGIC_LINK_COOLDOWN: "LOGIN_MAGIC_LINK_COOLDOWN",
  LOGIN_MAGIC_LINK_INVALID: "LOGIN_MAGIC_LINK_INVALID",
  LOGIN_USER_NOT_FOUND: "LOGIN_USER_NOT_FOUND",

  // ── Signup ──
  SIGNUP_EMAIL_EXISTS: "SIGNUP_EMAIL_EXISTS",
  SIGNUP_OTP_COOLDOWN: "SIGNUP_OTP_COOLDOWN",
  SIGNUP_OTP_LOCKED: "SIGNUP_OTP_LOCKED",
  SIGNUP_OTP_INVALID: "SIGNUP_OTP_INVALID",
  SIGNUP_RESEND_LIMIT: "SIGNUP_RESEND_LIMIT",
  SIGNUP_SESSION_INVALID: "SIGNUP_SESSION_INVALID",

  // ── Forgot Password ──
  FORGOT_PASSWORD_OTP_COOLDOWN: "FORGOT_PASSWORD_OTP_COOLDOWN",
  FORGOT_PASSWORD_OTP_RESEND_LIMIT: "FORGOT_PASSWORD_OTP_RESEND_LIMIT",
  FORGOT_PASSWORD_AUTH_NOT_FOUND: "FORGOT_PASSWORD_AUTH_NOT_FOUND",
  FORGOT_PASSWORD_OTP_LOCKED: "FORGOT_PASSWORD_OTP_LOCKED",
  FORGOT_PASSWORD_OTP_INVALID: "FORGOT_PASSWORD_OTP_INVALID",
  FORGOT_PASSWORD_MAGIC_LINK_COOLDOWN: "FORGOT_PASSWORD_MAGIC_LINK_COOLDOWN",
  FORGOT_PASSWORD_MAGIC_LINK_RESEND_LIMIT:
    "FORGOT_PASSWORD_MAGIC_LINK_RESEND_LIMIT",
  FORGOT_PASSWORD_MAGIC_LINK_INVALID: "FORGOT_PASSWORD_MAGIC_LINK_INVALID",
  FORGOT_PASSWORD_INVALID_RESET_TOKEN: "FORGOT_PASSWORD_INVALID_RESET_TOKEN",

  // ── Unlock Account ──
  UNLOCK_COOLDOWN: "UNLOCK_COOLDOWN",
  UNLOCK_RATE_LIMIT: "UNLOCK_RATE_LIMIT",
  UNLOCK_ACCOUNT_DISABLED: "UNLOCK_ACCOUNT_DISABLED",
  UNLOCK_ACCOUNT_NOT_LOCKED: "UNLOCK_ACCOUNT_NOT_LOCKED",
  UNLOCK_AUTH_NOT_FOUND: "UNLOCK_AUTH_NOT_FOUND",
  UNLOCK_INVALID_TEMP_PASSWORD: "UNLOCK_INVALID_TEMP_PASSWORD",
  UNLOCK_TEMP_PASSWORD_EXPIRED: "UNLOCK_TEMP_PASSWORD_EXPIRED",
  UNLOCK_USER_NOT_FOUND: "UNLOCK_USER_NOT_FOUND",

  // ── User ──
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_NO_FILE_UPLOADED: "USER_NO_FILE_UPLOADED",

  // ── File Upload ──
  FILE_TYPE_NOT_SUPPORTED: "FILE_TYPE_NOT_SUPPORTED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",

  // ── Contact Admin ──
  CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",

  // ── Blog ──
  BLOG_COVER_IMAGE_CONFLICT: "BLOG_COVER_IMAGE_CONFLICT",
  BLOG_NOT_FOUND: "BLOG_NOT_FOUND",
  BLOG_FORBIDDEN: "BLOG_FORBIDDEN",
  BLOG_CATEGORY_EXISTS: "BLOG_CATEGORY_EXISTS",
  BLOG_TAG_EXISTS: "BLOG_TAG_EXISTS",

  // ── Validation ──
  VALIDATION_EMAIL_REQUIRED: "VALIDATION_EMAIL_REQUIRED",
  VALIDATION_EMAIL_INVALID: "VALIDATION_EMAIL_INVALID",
  VALIDATION_OBJECT_ID_REQUIRED: "VALIDATION_OBJECT_ID_REQUIRED",
  VALIDATION_OBJECT_ID_INVALID: "VALIDATION_OBJECT_ID_INVALID",
  VALIDATION_FIELD_REQUIRED: "VALIDATION_FIELD_REQUIRED",
  VALIDATION_FIELD_TOO_SHORT: "VALIDATION_FIELD_TOO_SHORT",
  VALIDATION_FIELD_TOO_LONG: "VALIDATION_FIELD_TOO_LONG"
} as const;
