export const DEVICE_TYPES = {
  DESKTOP: "DESKTOP",
  MOBILE: "MOBILE",
  TABLET: "TABLET",
  UNKNOWN: "UNKNOWN"
} as const;

export const CLIENT_TYPES = {
  WEB: "WEB",
  MOBILE_IOS: "MOBILE_IOS",
  MOBILE_ANDROID: "MOBILE_ANDROID"
} as const;

export const GEO_DEFAULTS = {
  UNKNOWN_COUNTRY: "UNKNOWN",
  UNKNOWN_CITY: "UNKNOWN",
  UNKNOWN_IP: "UNKNOWN"
} as const;

export const USER_AGENT_DEFAULTS = {
  UNKNOWN_DEVICE: "UNKNOWN",
  UNKNOWN_OS: "UNKNOWN",
  UNKNOWN_BROWSER: "UNKNOWN"
} as const;
